module.exports = {
    content: [
        "./components/**/*.{js,jsx,ts,tsx}",
        "./lib/**/*.{js,jsx,ts,tsx}",
        "./views/**/*.{js,jsx,ts,tsx}",
        "./pages/**/*.{js,jsx,ts,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "colorPrimary": "#4385f3",
                "colorMain": "#4385f3",
                "colorPrimaryDark": "#356AC2",
                "colorPrimaryLight1": "#7ba9f6",
                "colorPrimaryLight2": "#64B5F6",
                "colorPrimaryLight3": "#42A5F5",
                "colorPrimaryLight4": "#2196F3",
                "colorAccent": "#3c3c3c",
                "colorBottomSheet": "#D94385f3",
                "colorBottomSheetRed": "#D9EF5350",
                "colorBottomSheetGreen": "#D900C853",
                "colorPureWhite": "#FFFFFF",
                "colorWhite": "#FAFAFA",
                "colorGrey0": "#F5F5F5",
                "colorGrey1": "#f1f1f1",
                "colorGrey2": "#e9e9e9",
                "colorGrey3": "#E0E0E0",
                "colorGrey4": "#BDBDBD",
                "colorGrey5": "#9c9c9c",
                "colorGrey6": "#616161",
                "colorPureBlack": "#000000",
                "colorText": "#212121",
                "colorTextBold": "#373737",
                "colorTextLight": "#424242",
                "colorGreen0": "#00C853",
                "colorGreen1": "#00E676",
                "colorGreen2": "#81C784",
                "colorGreen3": "#B3E09C",
                "colorYellow0": "#F9A825",
                "colorYellow1": "#FBC02D",
                "colorYellow2": "#FDD835",
                "colorBlueGrey0": "#f7f8f9",
                "colorBlueGrey1": "#ECEFF1",
                "colorBlueGrey2": "#CFD8DC",
                "colorRed0": "#E53935",
                "colorRed1": "#FFFD5900",
                "colorRed2": "#EF5350",
                "colorRed3": "#E57373",
                "colorBackgroundAdPlaceholder": "#dddddd",
                "colorBackgroundAdsImage": "#151515",
                "colorLandingGreenLight": "#22D12A",
                "colorLandingGreenDark": "#2BB673",
                "colorLandingBlue": "#698AFF",
                "colorLandingAqua": "#7DF7FF",
                "colorLandingEmerald": "#7DFFD0",
                "colorLandingTextBold": "#474747",
                "colorLandingTextLight": "#888888",
                "colorLandingDivider": "#D9D9D9",
                "colorProgressTrail": "#D5D5D5",
            },
            zIndex: {
                '100': '100'
            },
            width: {
                '15': '3.75rem',
                '18': '4.5rem',
                '22': '5.5rem',
                '50': '12.5rem',
                '100': '25rem',
                '120': '30rem',
                '140': '35rem',
                '150': '40rem'
            },
            height: {
                '15': '3.75rem',
                '18': '4.5rem',
                '22': '5.5rem',
                '50': '12.5rem',
                '100': '25rem',
                '120': '30rem',
                '140': '35rem',
                '150': '40rem'
            },
            padding: {
                '18': '4.5rem',
                '22': '5.5rem',
                '26': '6.5rem',
            }
        }
    },
    plugins: []
}
